# Generated by Django 5.2.7 on 2025-11-04 13:26

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa_credit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Основна сума кредиту')),
                ('percent', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Добова відсоткова ставка (%)')),
                ('start_date', models.DateField(verbose_name='Дата видачі')),
                ('srok_months', models.IntegerField(verbose_name='Термін кредиту (місяці)')),
                ('day_of_pay', models.IntegerField(default=1, help_text='День місяця (від 1 до 28), коли має бути платіж.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Плановий день оплати')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='credit_system.client', verbose_name='Клієнт')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума платежу')),
                ('date_pay', models.DateField(default=datetime.date.today, verbose_name='Дата платежу')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credit_system.credit', verbose_name='Кредит')),
            ],
        ),
    ]
