# Generated by Django 5.2.7 on 2025-11-05 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='IPN',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Введіть коректний ІПН. Поле має містити рівно 10 цифр, без літер та символів.')], verbose_name='ІПН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='middlename',
            field=models.CharField(default=1111111111, max_length=100, verbose_name='По-батькові'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credit',
            name='day_of_pay',
            field=models.IntegerField(default=15, help_text='День місяця (від 1 до 28), коли має бути платіж.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Плановий день оплати'),
        ),
    ]
