# Generated by Django 5.2.7 on 2025-11-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0002_client_ipn_client_middlename_alter_credit_day_of_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='middlename',
            new_name='middle_name',
        ),
    ]
